"""Add first and last name to User model

Revision ID: 277e7b080990
Revises: de07e4d2b58c
Create Date: 2024-07-27 19:39:40.615510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277e7b080990'
down_revision = 'de07e4d2b58c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
